
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS'
 */
public class card_game extends javax.swing.JFrame  {
  public class q extends Thread
  {
      public void run()
      {
          try {
              Thread.sleep(3000);
          
          BufferedImage b;
              try {
                  b = ImageIO.read(new File("E:\\downloads\\cards\\back\\c9e561d61fc50771ece1255125f7fb1a.jpg"));
                    jButton1.setIcon(new ImageIcon(b.getScaledInstance(jButton1.getWidth(), jButton1.getHeight(), WIDTH)));
               jButton2.setIcon(new ImageIcon(b.getScaledInstance(jButton2.getWidth(), jButton2.getHeight(), WIDTH)));
                jButton3.setIcon(new ImageIcon(b.getScaledInstance(jButton3.getWidth(), jButton3.getHeight(), WIDTH)));
                 jButton4.setIcon(new ImageIcon(b.getScaledInstance(jButton4.getWidth(), jButton4.getHeight(), WIDTH)));
                  jButton5.setIcon(new ImageIcon(b.getScaledInstance(jButton5.getWidth(), jButton5.getHeight(), WIDTH)));
                   jButton6.setIcon(new ImageIcon(b.getScaledInstance(jButton6.getWidth(), jButton6.getHeight(), WIDTH)));
                    jButton7.setIcon(new ImageIcon(b.getScaledInstance(jButton7.getWidth(), jButton7.getHeight(), WIDTH)));
                     jButton9.setIcon(new ImageIcon(b.getScaledInstance(jButton9.getWidth(), jButton9.getHeight(), WIDTH)));
                   jButton10.setIcon(new ImageIcon(b.getScaledInstance(jButton10.getWidth(), jButton10.getHeight(), WIDTH)));
                     
              } catch (IOException ex) {
                  Logger.getLogger(card_game.class.getName()).log(Level.SEVERE, null, ex);
              }
            
                       
              
              
          } catch (InterruptedException ex) {
              Logger.getLogger(card_game.class.getName()).log(Level.SEVERE, null, ex);
          }
      }
  }

    /**
     * Creates new form card_game
     */
    public card_game() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    String Q;
    int q,p;
    int n[]=new int [10];
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jButton8.setText("jButton8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton11.setText("start");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel1.setText(".");

        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton11)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
       
        q w=new q();
        
        Random r=new Random();
         
        JFileChooser j=new JFileChooser();
        j.showOpenDialog(jLabel1);
        
        File f=j.getCurrentDirectory();
        //String t ="E:\\downloads\\cards\\front";
        File f1[]=f.listFiles();
        int  a=r.nextInt(8);
        int m,l;
        
        for(m=0;m<=8;m++)
        {
         for(l=0;l<=8;l++)
         {
             if(m!=l)
             {
             while(n[m]==n[l])
             {
                 n[m]=r.nextInt(8);
             }
             }
         }
        }
         for(m=0;m<=8;m++)
         {
             System.out.println("\n"+n[m]);
         }
        
         p=r.nextInt(8);
       // ArrayList<f> a=ArrayList<>();
        try {
            BufferedImage b=ImageIO.read(new File(f1[p].getPath()));
            jLabel1.setIcon(new ImageIcon(b.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), WIDTH)));
            
           
            
        } catch (IOException ex) {
            Logger.getLogger(photo.class.getName()).log(Level.SEVERE, null, ex);
        }
        BufferedImage b;
        try {
            b = ImageIO.read(new File(f1[n[0]].getPath()));
            jButton1.setIcon(new ImageIcon(b.getScaledInstance(jButton1.getWidth(), jButton1.getHeight(), WIDTH)));
        } catch (IOException ex) {
            Logger.getLogger(card_game.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            b = ImageIO.read(new File(f1[n[1]].getPath()));
            jButton2.setIcon(new ImageIcon(b.getScaledInstance(jButton2.getWidth(), jButton2.getHeight(), WIDTH)));
        } catch (IOException ex) {
            Logger.getLogger(card_game.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            b = ImageIO.read(new File(f1[n[2]].getPath()));
            jButton3.setIcon(new ImageIcon(b.getScaledInstance(jButton3.getWidth(), jButton3.getHeight(), WIDTH)));
        } catch (IOException ex) {
            Logger.getLogger(card_game.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            b = ImageIO.read(new File(f1[n[3]].getPath()));
            jButton4.setIcon(new ImageIcon(b.getScaledInstance(jButton4.getWidth(), jButton4.getHeight(), WIDTH)));
        } catch (IOException ex) {
            Logger.getLogger(card_game.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            b = ImageIO.read(new File(f1[n[4]].getPath()));
            jButton5.setIcon(new ImageIcon(b.getScaledInstance(jButton5.getWidth(), jButton5.getHeight(), WIDTH)));
        } catch (IOException ex) {
            Logger.getLogger(card_game.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            b = ImageIO.read(new File(f1[n[5]].getPath()));
            jButton6.setIcon(new ImageIcon(b.getScaledInstance(jButton6.getWidth(), jButton6.getHeight(), WIDTH)));
        } catch (IOException ex) {
            Logger.getLogger(card_game.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            b = ImageIO.read(new File(f1[n[6]].getPath()));
            jButton7.setIcon(new ImageIcon(b.getScaledInstance(jButton7.getWidth(), jButton7.getHeight(), WIDTH)));
        } catch (IOException ex) {
            Logger.getLogger(card_game.class.getName()).log(Level.SEVERE, null, ex);
        }
        
     try {
            b = ImageIO.read(new File(f1[n[7]].getPath()));
            jButton9.setIcon(new ImageIcon(b.getScaledInstance(jButton9.getWidth(), jButton9.getHeight(), WIDTH)));
        } catch (IOException ex) {
            Logger.getLogger(card_game.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        try {
            b = ImageIO.read(new File(f1[n[8]].getPath()));
            jButton10.setIcon(new ImageIcon(b.getScaledInstance(jButton10.getWidth(), jButton10.getHeight(), WIDTH)));
        } catch (IOException ex) {
            Logger.getLogger(card_game.class.getName()).log(Level.SEVERE, null, ex);
        }
        w.start();
        
           //jLabel1.setIcon(new ImageIcon(b.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), WIDTH)));
           
        
        
        
        
        
        
        
//        try {
//            BufferedImage b=ImageIO.read(new File(f.getPath()));
//            jLabel1.setIcon(new ImageIcon(b.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), WIDTH)));
//            
//        } catch (IOException ex) {
//            Logger.getLogger(photo.class.getName()).log(Level.SEVERE, null, ex);
//        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
if(n[1]==p)
{
    jLabel2.setText("won!!");
}
else
{
    jLabel2.setText("lose!!");
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
if(n[2]==p)
{
    jLabel2.setText("won!!");
}
else
{
    jLabel2.setText("lose!!");
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
if(n[3]==p)
{
    jLabel2.setText("won!!");
}
else
{
    jLabel2.setText("lose!!");
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
if(n[4]==p)
{
    jLabel2.setText("won!!");
}
else
{
    jLabel2.setText("lose!!");
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
if(n[6]==p)
{
    jLabel2.setText("won!!");
}
else
{
    jLabel2.setText("lose!!");
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
if(n[7]==p)
{
    jLabel2.setText("won!!");
}
else
{
    jLabel2.setText("lose!!");
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(n[0]==p)
{
    jLabel2.setText("won!!");
}
else
{
    jLabel2.setText("lose!!");
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
if(n[5]==p)
{
    jLabel2.setText("won!!");
}
else
{
    jLabel2.setText("lose!!");
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
if(n[8]==p)
{
    jLabel2.setText("won!!");
}
else
{
    jLabel2.setText("lose!!");
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(card_game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(card_game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(card_game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(card_game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new card_game().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
